CREATE table Peliculas(
    pel_id int primary key,
    pel_resumen text,
    pel_año int,
    pel_director int,

    FOREIGN KEY (pel_id) REFERENCES Contenidos (contenido_id),
    FOREIGN KEY (pel_director) REFERENCES Director (director_id)
    );

INSERT into Peliculas values(01, "Aventura submarina que narra con humor el viaje que realiza Marlin, un sobreprotector pez payaso padre, en busca de su hijo Nemo, cuando este es llevado a la pecera de un dentista en Sídney. Una despistada y algo exasperante pez llamada Dory acompañará a Marlin en un viaje lleno de peligros inesperados y momentos muy divertidos.", 2003, 01),
                            (02, "Mérida es una princesa poco habitual, monta a caballo y maneja el arco mejor que cualquier guerrero de su reino. Continuando la tradición, el Rey Fergus y la Reina Elinor quieren casarla con el hijo del rey de uno de los tres clanes aliados. Para saber quién será su futuro marido se celebra un torneo, donde los tres pretendientes demostrarán sus actitudes bélicas. Negándose a ser un trofeo, Mérida escapa del reino y llega a la casa de una hechicera donde tomará una decisión que pondrá en peligro al reino y a su familia. Pero el valor y el coraje de esta joven pelirroja al enfrentarse a su destino, nos harán disfrutar de una gran aventura situada en las tierras mágicas de Escocia.", 2012, 02),
                            (03, "Es la única película de la lista que no es de animación, además tiene ya unos años (1993), pero es una de las comedias más divertidas para disfrutar en familia. ¿Os imagináis una canguro de edad avanzada, que en realidad es el padre de los niños a los que cuida? Este es el papel que interpreta Robin Williams en esta película tan divertida que ganó un globo de oro al mejor actor y que actualmente está rodando una secuela.", 1993, 03),
                            (04, "Cuando Mavis, la hija del legendario Drácula cumple 118 años su padre celebra una fiesta por todo lo alto. Para ello invita a todos los monstruos del mundo al hotel que regenta, un hotel muy especial construido para mantener ocultos y a salvo de los humanos a todos los monstruos. Pero un intrépido viajero de 21 años se cuela sin querer en el castillo durante el trascurso de la fiesta. ¿Cómo reacciona Drácula, cuando descubre que su hija se interesa por conocer a este “peligroso” humano? Disfrutaréis de momentos muy divertidos a lo largo de esta película junto con hombres lobo, momias, zombis, un excéntrico hombre invisible y el mismísimo Frankenstein.", 2021, 04),
                            (05, "Hipo es el hijo del jefe de una tribu vikinga, pero es todo lo contrario a un vikingo, no le gustan las armas, es enclenque y bastante despistado. Su sueño es atrapar a un dragón de los que asolan su poblado, para así ganarse el respeto de los demás. Usando su ingenio construye un artefacto con el que atrapa sorprendentemente a uno de los dragones más peligrosos. El dragón terminará convirtiendose en su mejor amigo, y por este motivo Hipo se enfrentará a su padre, al poblado y a las ancestrales costumbres vikingas, pero les enseñará a todos una valiosa lección: las apariencias engañan.", 2010, 05);
